libs/sysplugins/smarty_internal_compile_private_special_variable.php
on undefined constants you get 'TEST_CONST' on definied constants TEST_CONST
fix #28
=> fix constant handling

.gitignore
git ignore pattern .idea\ causes version control in netbeans 8.02 to crash
=> removed invalid .gitignore pattern

libs/plugins/modifier.regex_replace.php
Hi,
just a small improvement to the regex_replace modifier, that add support for the $limit parameter
Cheers
=> Added $limit parameter to regex_replace modifier

README.md
- Wrap JSON examples in language specific code wraps.
- Use quotes to highlight features.
=> Refactor readme: use github markdown parser

README.md
Just fix README markdown titles
=> Fix markdown titles

NEW_FEATURES.txt
function is actually 'setLiterals' but docs refer to 'setLiteral'
=> minor typo in NEW_FEATURES.txt (setLiterals)

change_log.txt
=> Fixes the change log date of the 3.1.34 release

libs/sysplugins/smarty_internal_templatelexer.php
Added space between 'line' and line number.
=> Typo in exception message

libs/sysplugins/smarty_internal_templateparser.php
=> fix minor typo

CHANGELOG.md, lexer/smarty_internal_templateparser.y
=> Brought lexer source functionally up-to-date with compiled version

tests/UnitTests/TemplateSource/ValueTests/Variables/Stream/StreamVariableTest.php
=> Fix typo in StreamVariableTest.php

libs/plugins/shared.mb_str_replace.php
$parts must be an array, because the argument for count() must be countable, mb_split() returns an array or a boolean.
=> Fix for php 8.0

CHANGELOG.md, libs/plugins/function.math.php, tests/UnitTests/TemplateSource/ValueTests/Math/MathTest.php
=> Support multiple operators in math equations

libs/plugins/function.math.php, tests/UnitTests/TemplateSource/ValueTests/Math/MathTest.php
Try to fix https://github.com/smarty-php/smarty/issues/721
=> math equation return warning: max(x, y)

CHANGELOG.md, demo/plugins/cacheresource.pdo.php
=> Fix PHP 8.1 deprecation notices in demo/plugins/cacheresource.pdo.php

libs/debug.tpl
* Replace deprecated tags
* Use CSS3 selectors
* Update html-frame
* Remove deprecated syntax
* Harmonize syntax in general
=> Update to HTML5-syntax in debug template

CHANGELOG.md, libs/plugins/modifiercompiler.unescape.php, tests/UnitTests/TemplateSource/TagTests/PluginModifier/PluginModifierUnescapeTest.php
=> Fixed second param of unescape modifier

CHANGELOG.md, libs/sysplugins/smarty_internal_templatebase.php
=> clean output buffer for Throwable instead of just Exception

CHANGELOG.md, libs/plugins/function.html_select_date.php, libs/plugins/modifier.date_format.php
=> Silence deprecation errors for strtime in PHP8.1 or higher

CHANGELOG.md, libs/plugins/modifiercompiler.strip_tags.php, tests/UnitTests/TemplateSource/TagTests/PluginModifier/PluginModifierStripTagsTest.php
=> Fix strip_tags modifier for falsy input.

docs/designers/language-builtin-functions/language-function-include.md, docs/designers/language-builtin-functions/language-function-section.md
Hi, I believe I've found some typos in documentation examples.
=> Typos in documentation

CHANGELOG.md, libs/sysplugins/smarty_internal_compile_private_print_expression.php
=> Fix incorrect compilation of expressions when escape_html=true

changelog/952.md, src/Compile/Tag/FunctionClose.php, src/Data.php, src/Runtime/TplFunctionRuntime.php, src/Template.php, src/TemplateBase.php, tests/UnitTests/TemplateSource/X_Scopes/ScopeTest.php, tests/UnitTests/__shared/PHPunitplugins/function.checkvar.php
=> Fixed that scoped variables would overwrite parent scope.

changelog/994.md, src/Data.php, tests/UnitTests/SmartyMethodsTests/GetTemplateVars/GetTemplateVarsTest.php
=> Fix change in signature of getTemplateVars

changelog/1074.md, src/BlockHandler/BlockPluginWrapper.php, src/Compiler/Template.php, src/Extension/CallbackWrapper.php, src/Runtime/DefaultPluginHandlerRuntime.php, src/Template/Source.php
=> replace/qualify call_user_func_array.

docs/designers/language-modifiers/language-modifier-empty.md, docs/designers/language-modifiers/language-modifier-in_array.md, mkdocs.yml
empty and in_array modifiers are not listed in Modifiers list of the doc.
=> add empty and in_array modifier doc
