libs/sysplugins/smarty_internal_extension_config.php
=> fix variable name

README
The existing README states that 3 params are passed for plugins (params, smarty, template) but the smarty object was actually removed long ago. This update corrects this.
=> Update README with correct plugin method signature

libs/Smarty.class.php
loading it from include path (without abs path) can be dangerous, can load some other project's Autoloader.php instead the right one.
=> do not load "Autoloader" from include path

libs/sysplugins/smarty_internal_templatecompilerbase.php
Explicitly defining the evaluation order with the curly braces.
In PHP5
``
$person->$property['first'] is evaluated as $person->{$property['first']}
``
But in PHP7
``
$person->$property['first'] is evaluated as {$person->$property}['first']
``
=> Compatible with PHP7

libs/sysplugins/smarty_internal_data.php
I added `Smarty_Internal_Data::getVariable()` which equally uses lazy loaded external plugin as  `getTemplateVars()`. I also added a deprecation message so that it is clear it will be removed soon. 
As it is  version 3.1.28 breaks existing code written in 3.1.27, which violates the SemVer principle.
=> Restored Smarty_Internal_Data::getVariable()

libs/sysplugins/smarty_internal_method_compilealltemplates.php
When the template is in a subdirectory of the sourcedir, the the template could not be loaded
=> set correct path to template in CompileAll

libs/sysplugins/smarty_internal_data.php
Removed the extra if block, when an array has been given as the $tpl_var argument, because in the else block there is already a "not empty check".
=> Minor optimization for Smarty_Internal_Data::assign()

libs/sysplugins/smarty_internal_compile_private_object_function.php
This changes need to correct definition methods in registered objects with `__call` method;
```
class ObjectWithMagicCall {
public function __call() {
...
return 'some-value';
}
}
```
```
$smarty -> registerObject('registered_object', new ObjectWithMagicCall())
```
if we use method in template  `{registered_object->magicMethod assign="res"}`, method magicMethod will be defined as property.
=> Fix define method in registered objects

.gitattributes
add files to be excluded from git export
visible when used via composer --prefer-dist or just by downloading .zip or .tar.gz from github releases page
=> exclude files from git export

libs/sysplugins/smarty_internal_templatebase.php
It's `setDefaultModifiers()`, not `setDefaultModifier()`
=> Fix typo in @method annotation

INHERITANCE_RELEASE_NOTES.txt, NEW_FEATURES.txt, README, SMARTY_3.0_BC_NOTES.txt, SMARTY_3.1_NOTES.txt, demo/plugins/cacheresource.pdo.php, lexer/smarty_internal_templateparser.y, libs/plugins/function.mailto.php, libs/sysplugins/smarty_internal_compile_private_registered_function.php, libs/sysplugins/smarty_internal_runtime_inheritance.php, libs/sysplugins/smarty_internal_runtime_updatescope.php
patch contains some spelling fixes ( just in comments ) as found by a bot ( http://www.misfix.org, https://github.com/ka7/misspell_fixer ). Any upcoming License changes (e.g. GPL2 to GPL3+) are hereby granted.
=> spelling fixes

libs/Smarty.class.php
Param of [addPluginsDir()](http://www.smarty.net/docs/en/api.add.plugins.dir.tpl) can be null, array or a string. Fixed annotation so there will be no IDE warnings.
=> Fix annotation for addPluginsDir()

libs/sysplugins/smarty_internal_templatebase.php
`callback` is not a valid PHP type and makes static analysis tools failing
=> Replace callback typehint with callable

README.md
Hi ! I wanted to make sure Smarty is compatible with php7.3 and php7.4 and it was not obvious at 1st glance. So I suggest the following enhancements to help other people with the same question.
=> Add Travis badge and php compatibility infos in readme

libs/Smarty_Compiler.class.php
Calling Smarty 2.x foreach on an StdClass parameter, triggers a warning on PHP 7.2+ 
StdClass is commonly present after deserialising an object via json_decode/unserialize.
Historically this has worked fine in Smarty 2.x, without the StdClass having to be cast to an array first, but now triggers a warning on PHP 7.2+
This commits just adds an edge case to explicitly cast StdClass to an array, to prevent the warning but also without breaking support for previous PHP versions.
Note that PHP 5 introduced the Countable interface, which looked like a tempting solution.
But even in PHP 7.2+, StdClass returns false for `instanceof Countable` so is not usable anyway
Would be grateful to see this merged into 2.x branch.
=> allow StdClass to be cast to array when compiling foreach, to prevent invalid count warning in PHP 7.2+

demo/plugins/cacheresource.memcache.php
The set and get method of class memcached needs different parameters than class memcache. Therefore, it must be changed.
Memcached::get(string $key); can only get one value
Memcached::set (string $key , mixed $value , int $expiration); have only three parameters
=> Fixed using wrong get and set methods from class memcached

libs/sysplugins/smarty_internal_compile_assign.php
There was a problem when trying to assign a value to an object, as if it were an array
(using 42 as a placeholder)
```smarty
{$model.foo=42}
```
`$model` is an object, implementing the ArrayAccess interface, therefore it's usable as an array
Still, Smarty_Internal_Compile_Assign compiled that code like this:
```php
$_tmp_array = isset($_smarty_tpl->tpl_vars['model']) ? $_smarty_tpl->tpl_vars['model']->value : array(); // If variable exists, use that, otherwise use a brand new array
if (!is_array($_tmp_array) || $_tmp_array instanceof ArrayAccess) { // <-- Either wrong operator order or messed up De Morgan's law
settype($_tmp_array, 'array'); // Convert to array
}
$_tmp_array['foo'] = 42; // Assign the value to the key
$_smarty_tpl->_assignInScope('model', $_tmp_array); // Put it back in …
```
=> Fixing problem with assigning value to object variables as arrays in smarty_internal_compile_assign

.gitattributes
used only for travis testing. the file was added in 19ebab9e4a73b643e7bd137905a6e4e7025289c1
=> exclude error_reporting.ini from git export

libs/Smarty.class.php
Although this could be removed, but because the header comment is still there, it's a good idea to keep the @version tag up-to-date with the current working version in order to avoid confusion for those who still read it :)
=> Bumped phpdoc @version tag to 3.1.36

libs/sysplugins/smarty_internal_compile_private_special_variable.php
`const` condition fix introduced in PR #608.
Fixes #609
Fixes #613
=> `const` condition fix

libs/plugins/modifier.escape.php
I have found myself doing "....|escape:html_attr" or" ....|escape:quote" a few times. It'd help if there was some sort of warning logged if an unsupported escape type is used.
=> Naive attempt at stopping incorrect escape type being used

libs/plugins/modifier.escape.php, libs/plugins/modifiercompiler.escape.php
There are poor escaping for javascript now. See https://html.spec.whatwg.org/multipage/scripting.html#restrictions-for-contents-of-script-elements for details.
_test.php_
```
<?php
require_once('libs/Smarty.class.php');
$smarty = new Smarty();
$smarty->force_compile = true;
$smarty->caching = false;
$smarty->assign('name', "\abc\r\n\"'</script></Script></scripT><!--<script><Script><scripT>");
$smarty->display('test.tpl');
```
_test.tpl_
```
<script>
// if (x<!--y)
console.log('{$name|escape:'javascript'}')
console.log('next output')
</script>
<script>
console.log("{$name|escape:'javascript'}")
// if ( player<script )
console.log('next output')
</script>
<script>
console.log('next output')
</script>
```
```
\abc
"'</script></<Script></scripT><!--<script><<Script><scripT>
next output
\abc …
```
=> plugins: escape: javascript escaping secure fix

.github/workflows/ci.yml, libs/sysplugins/smarty_internal_cacheresource_file.php, libs/sysplugins/smarty_internal_compile_function.php, libs/sysplugins/smarty_internal_config_file_compiler.php, libs/sysplugins/smarty_internal_runtime_codeframe.php, libs/sysplugins/smarty_internal_templatecompilerbase.php, libs/sysplugins/smartycompilerexception.php, tests/UnitTests/CacheResourceTests/_shared/CacheResourceTestCommon.php, tests/UnitTests/ResourceTests/Stream/StreamResourceTest.php, tests/UnitTests/SecurityTests/SecurityTest.php, tests/UnitTests/TemplateSource/TagTests/TemplateFunction/CompileFunctionTest.php, tests/UnitTests/TemplateSource/ValueTests/Variables/Stream/StreamVariableTest.php
This is the follow-up for https://github.com/smarty-php/smarty/pull/711. I tried to keep as many commits without modification here. Hope that's ok @GoT
I coudn't find a way to update the previous pr, sorry.
=> PHP 8.1 compatibility (without IntlDateFormatter)

.github/workflows/ci.yml, README.md, docs/getting-started.md
Additionally, I've activate jit as an additional compiler for 8.1 in the tests.
=> Updating PHP 8.0 to 8.1 in the docs.

CHANGELOG.md, libs/plugins/modifier.truncate.php
=> prevent float to int cast deprecation warning in truncate modifier

.gitattributes
`.github` wasn't added here was it got created. However, we don't want to include `.github` to release builds (e.g. when installing it through composer).
=> gitattributes: Ignore `.github` folder for distribution

libs/Smarty.class.php, libs/sysplugins/smarty_internal_compile_insert.php, tests/UnitTests/ResourceTests/Custom/Ambiguous/PHPunitplugins/resource.ambiguous.php
Fixes - Deprecated: rtrim(): Passing null to parameter #1 ($string) of type string is deprecated
=> Fix PHP 8.1 deprecated warning when calling rtrim

libs/plugins/modifier.escape.php, libs/plugins/modifiercompiler.escape.php
In PHP 8.1 is deprecated passing null parameters for string typed parameters. Escape modifier thrown this deprecation:
```
PHP Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in
```
PR fixes this issues.
=> PHP 8.1: fix deprecation in escape modifier

libs/sysplugins/smarty_internal_compile_private_print_expression.php
Fixes a remaining PHP 8.1 deprecation error for `htmlspecialchars` (issue #750) which was not covered by the PR #727.
=> Fix PHP 8.1 htmlspecialchars deprecation

libs/plugins/shared.mb_str_replace.php, tests/UnitTests/TemplateSource/_Issues/549/MbSplitEncodingIssue549Test.php, tests/UnitTests/TemplateSource/_Issues/549/cache/.gitignore, tests/UnitTests/TemplateSource/_Issues/549/templates_c/.gitignore
`mb_split` will fail if `$pattern` or `$string` contains byte sequences not valid for `mb_regex_encoding()`.
Convert both strings and set regex encoding before calling `mb_split()` if needed.
Fixes smarty-php#549
=> Fixed replace modifier by converting encoding if needed

libs/plugins/modifier.explode.php, libs/plugins/modifier.number_format.php, libs/plugins/shared.mb_str_replace.php, tests/UnitTests/TemplateSource/TagTests/PluginModifier/PluginModifierExplodeTest.php, tests/UnitTests/TemplateSource/TagTests/PluginModifier/PluginModifierNumberFormatTest.php, tests/UnitTests/TemplateSource/TagTests/PluginModifier/PluginModifierReplaceTest.php
This PR is meant to address several of the PHP 8.1 deprecation items noted in Issue #750 
It does not address the deprecation noted in 'escape' because I was not able to recreate the issue against the current master branch
It also does not address any strftime() related deprecation issues since it is not clear to me how that issue should be addressed as a whole. Discussions were present in #678 and touched on using an intl polyfill, but changes were deferred at that time.  #672 is open as a strftime() specific issue so I suppose it would still be handled there unless a decision has already been made, in which case I would be happy to update this PR once I know how it should be handled.
=> address PHP 8.1 'explode', 'number_format', and 'replace' deprecations

CHANGELOG.md, libs/plugins/function.math.php, tests/UnitTests/TemplateSource/ValueTests/Math/MathTest.php
=> Fixed use of `rand()` without a parameter in math function

libs/plugins/modifier.capitalize.php
Introduced in https://github.com/smarty-php/smarty/commit/d304d349b4deb19c84742b29b53bb3f8e59413fc
=> Fix wrong indentation in libs/plugins/modifier.capitalize.php

libs/sysplugins/smarty_internal_template.php
We maintain a complex template setup using inheritance and includes. 
When activating caching, we get an out of memory error due to a non-terminating recursion. 
After stepping through the code there seem to be two possible causes, which when corrected resolve the issue.
The first one being missing parenthesis around the ternary operator which leads to a wrong comparison.
With the second one it seems that the wrong template was compiled.
PHP-version: 8.0
Smarty-version: 4.2.0
=> fix compilation for caching templates

libs/sysplugins/smarty_cacheresource_keyvaluestore.php
Fixed a PHP 8.1 deprecation error:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in cacheresource_keyvaluestore.php on line 247 and in cacheresource_keyvaluestore.php on line 431
=> Fixed PHP8.1 deprecation errors passing null to parameter in trim

CHANGELOG.md, libs/plugins/modifier.count.php, libs/plugins/modifiercompiler.nl2br.php, libs/plugins/modifiercompiler.round.php, libs/plugins/modifiercompiler.str_repeat.php, libs/plugins/modifiercompiler.strlen.php, libs/sysplugins/smarty_internal_compile_private_modifier.php, libs/sysplugins/smarty_security.php, tests/UnitTests/SecurityTests/SecurityTest.php, tests/UnitTests/SmartyMethodsTests/RegisterBlock/RegisterBlockTest.php, tests/UnitTests/SmartyMethodsTests/RegisterObject/CompileRegisteredObjectFunctionTest.php, tests/UnitTests/TemplateSource/TagTests/Append/CompileAppendTest.php, tests/UnitTests/TemplateSource/TagTests/Assign/CompileAssignTest.php, tests/UnitTests/TemplateSource/TagTests/If/CompileIfTest.php, tests/UnitTests/TemplateSource/TagTests/PluginModifier/PluginModifierCountTest.php, tests/UnitTests/TemplateSource/TagTests/PluginModifier/PluginModifierExplodeTest.php, tests/UnitTests/TemplateSource/TagTests/PluginModifier/PluginModifierNl2brTest.php, tests/UnitTests/TemplateSource/TagTests/PluginModifier/PluginModifierStrRepeatTest.php, tests/UnitTests/TemplateSource/ValueTests/Math/MathTest.php, tests/UnitTests/TemplateSource/_Issues/327/ModifierIssue327Test.php
=> Using PHP functions as modifiers now triggers a deprecation notice.

.github/workflows/ci.yml, CHANGELOG.md, README.md, docker-compose.yml, docs/getting-started.md, libs/plugins/modifier.escape.php, libs/plugins/modifiercompiler.escape.php, libs/plugins/modifiercompiler.unescape.php, libs/sysplugins/smarty_internal_extension_handler.php, libs/sysplugins/smarty_internal_runtime_make_nocache.php, libs/sysplugins/smarty_internal_template.php, libs/sysplugins/smarty_security.php, libs/sysplugins/smarty_variable.php, tests/UnitTests/ResourceTests/Stream/StreamResourceTest.php, tests/UnitTests/SecurityTests/SecurityTest.php, tests/UnitTests/SmartyMethodsTests/RegisterObject/CompileRegisteredObjectFunctionTest.php, tests/UnitTests/TemplateSource/TagTests/PluginModifier/PluginModifierCharsetTest.php, tests/UnitTests/TemplateSource/TagTests/PluginModifier/PluginModifierEscapeTest.php, tests/UnitTests/TemplateSource/TagTests/PluginModifier/PluginModifierStripTest.php, tests/UnitTests/TemplateSource/TagTests/PluginModifier/PluginModifierUnescapeTest.php, tests/UnitTests/TemplateSource/ValueTests/Variables/Stream/StreamVariableTest.php, utilities/testrunners/php82/Dockerfile
Added suport for PHP8.2 compatibility.
Thanks @ophian
=> PHP8.2 compatibility

CHANGELOG.md, libs/sysplugins/smarty_internal_runtime_writefile.php
=> Change file permissions for directories and respect umask for files

CHANGELOG.md, libs/sysplugins/smarty_internal_errorhandler.php, tests/UnitTests/A_2/UndefinedTemplateVar/UndefinedTemplateVarTest.php
=> Allow dereferencing of non-objects accross all supported PHP versions

CHANGELOG.md, libs/plugins/modifier.truncate.php, libs/plugins/modifiercompiler.count_characters.php, libs/plugins/modifiercompiler.count_words.php, libs/plugins/modifiercompiler.lower.php, libs/plugins/modifiercompiler.upper.php, libs/plugins/outputfilter.trimwhitespace.php, libs/plugins/shared.escape_special_chars.php, libs/plugins/variablefilter.htmlspecialchars.php
I noticed that if one is calling `|truncate` on null, it triggers `E_DEPRECATED: mb_strlen(): Passing null to parameter #1 ($string) of type string is deprecated` on PHP 8.1.
This is expected, but given the modifier accepts null we may as well return an empty string before calling the function.
=> Fix PHP8.1 deprecation warnings on null string in modifiers

.github/workflows/ci.yml
This PR upgrades `actions/checkout` and `actions/cache` used in GitHub actions to reduce 40 warnings shown in the [action page](https://github.com/smarty-php/smarty/actions/runs/4257111806).
=> Upgrade actions/checkout and actions/cache

libs/debug.tpl, libs/sysplugins/smarty_internal_debug.php
Replaced with a regular function call. 
See https://github.com/smarty-php/smarty/issues/813
=> Remove `md5` modifier from debug.tpl

CHANGELOG.md, src/FunctionHandler/Math.php, tests/UnitTests/TemplateSource/ValueTests/Math/MathTest.php
=> Fix use of negative numbers in math equations.

src/Compiler/Template.php, src/Security.php, tests/UnitTests/SmartyMethodsTests/RegisterFunction/RegisterFunctionTest.php
This should fix #907. 
All tests pass, I thought about adding more tests for various plugins but it seemed overkill, happy to add them if the reviewer thinks otherwise. 
There might be a regression here (I don't think so) but just so everyone is aware this will start failing: 
```
$smarty = new Smarty();
$smarty->registerPlugin(Smarty::PLUGIN_FUNCTION, 'customtag', [Functions::class, 'customTag']);
$smarty->display('string:{customTag}');
```
I have kept the "built-in" tags case-insensitive because they have been relying on them being lowercase, so I think it is sensible to keep it this way.
=> Fix case-sensitive tag names (#907)

CHANGELOG.md, src/Debug.php, src/Smarty.php, src/debug.tpl, tests/UnitTests/TemplateSource/TagTests/Debug/DebugTest.php
=> Fixed failing {debug} tag.

.github/workflows/ci.yml, CHANGELOG.md, docker-compose.yml, run-tests-for-all-php-versions.sh, src/ErrorHandler.php, utilities/testrunners/php83/Dockerfile
=> Add php8.3 support

changelog/935.md, docs/upgrading.md, src/Compiler/CodeFrame.php, src/Compiler/Template.php, src/Template/Source.php
=> Add template path to CompilerException to enable rich debug features

CHANGELOG.md, lexer/smarty_internal_templateparser.y, libs/sysplugins/smarty_internal_compile_private_modifier.php, libs/sysplugins/smarty_internal_templatecompilerbase.php, libs/sysplugins/smarty_internal_templateparser.php, libs/sysplugins/smarty_security.php, phpunit.xml, run-tests-for-all-php-versions.sh, tests/PHPUnit_Smarty.php, tests/UnitTests/A_Core/LoadPlugin/LoadPluginTest.php, tests/UnitTests/SecurityTests/SecurityTest.php, tests/UnitTests/SmartyMethodsTests/ClearAllAssign/ClearAllAssignTest.php, tests/UnitTests/TemplateSource/ValueTests/PHPfunctions/PhpFunctionTest.php
... because we will drop support for this in the next major release
Fixes #813
=> Using PHP functions and static class methods in expressions now also triggers a deprecation notice

src/functions.php
Running the following template will result in a deprecation warning: 
`{20240301121415|date_format:"%d-%m-%Y"}`
Casting the value to string should a be a safe fix.
=> Deprecation fix for providing a non string value to ctype_digit

changelog/966.md, src/Smarty.php
=> Fix missing and bogus use lines in src/Smarty.php.

docs/designers/language-modifiers/language-modifier-is_array.md, mkdocs.yml
is_array exists in code and referenced in several documentation examples but is not listed in Modifiers list of the doc.
=> add is_array modifier doc

src/Smarty.php, src/TemplateBase.php
This PR fixes a couple of `UndefinedDocblockClass` issues that Psalm was throwing after the upgrade to version 5.
@wisskid Nice work on the new version 😄 I know you've caught some flack for some of the changes, but they are all for the good. We payed attention to the deprecation notices in v4 so it's gone smoothly (so far 🤞)
=> Fix docblock types

changelog/1000.md, src/Runtime/ForeachRuntime.php
=> Corrected invalid classnames in Runtime code for foreach

changelog/996.md, src/Compiler/Template.php, src/ParseTree/Dq.php, src/ParseTree/Tag.php, src/ParseTree/Template.php, src/Parser/TemplateParser.php, src/Parser/TemplateParser.y
=> Prevent notices on null to string conversion in Template::appendCode

docs/designers/language-builtin-functions/language-function-config-load.md, src/Compile/Tag/ConfigLoad.php
=> Remove unused attributes from config_load

changelog/1022.md, docs/api/configuring.md, src/Smarty.php, tests/UnitTests/ResourceTests/FileIndexed/FileResourceIndexedTest.php
=> implemented and documented prependTemplateDir.

changelog/1030.md, docs/api/configuring.md, docs/designers/language-modifiers/language-modifier-escape.md, docs/designers/language-modifiers/language-modifier-raw.md, mkdocs.yml, src/Compile/Modifier/EscapeModifierCompiler.php, src/Compile/Modifier/RawModifierCompiler.php, src/Compile/ModifierCompiler.php, src/Compile/PrintExpressionCompiler.php, src/Compiler/Template.php, src/Extension/DefaultExtension.php, src/Smarty.php, tests/UnitTests/A_Core/AutoEscape/AutoEscapeTest.php
This evolution improves the auto-escaping feature.
- The `escape` modifier has no effect when auto-escaping is enabled (when no escape format is given, or when the `html` format is used), to prevent double-escaping.
- The other formats of the `escape` modifier (`htmlall`, `url`, `urlpathinfo`, `quotes`, `javascript`) are processed as we may expect, without double-escaping.
- The new `force` format of the `escape` modifier allows to force double-escaping if needed.
- The new `raw` modifier temporary disables auto-escaping for the expression it is used on.
This Pull Request contains the source code of this evolution, as well as its documentation and unit tests.
=> Improvement of auto-escaping

src/debug.tpl
add missing end </tr> tag for 'assigned template variables' section.
it's also missing for the 4.x branch.
=> add missing closing tr tag

src/Resource/FilePlugin.php, src/Template/Compiled.php
Fixes: https://github.com/smarty-php/smarty/issues/1007
\Smarty\Template\Compiled::loadCompiledTemplate invalidates the cache entry of a compiled template on every call (or include) as it is forced to do so.
This results in fast growing wasted memory and after reaching the tipping point in a total cleanup and refresh of the opcache.
I do not think, that is necessary to force it, seeing this change as hotfix.
Nice article about wasted memory of the opcache and it's refreshment mechanism: 
https://www.codana.be/en/insights/php-opcache-realpath-cache-and-preloading
=> Fixing forced OpCache invalidation on every template include, which is resulting in fast raising wasted OpCache memory #1007

src/Resource/ExtendsPlugin.php
This PR fixes #1018 
And many of the errors detected by https://github.com/smarty-php/smarty/pull/1046#issuecomment-2257067168 will be corrected, too.
The filename in https://github.com/smarty-php/smarty/issues/1018#issuecomment-2137617407 will have “|” replaced by “.”  as follows on Windows only:
[Before]
- ./tests/UnitTests/ResourceTests/Extends/templates_c/0a382e517fefa510de3f987160291ed9924a7124_0.extends_050_parent.tpl|050_child.tpl|050_grandchild.tpl.php
[After]
- ./tests/UnitTests/ResourceTests/Extends/templates_c/0a382e517fefa510de3f987160291ed9924a7124_0.extends_050_parent.tpl.050_child.tpl.050_grandchild.tpl.php
How about this fix?
This feels like a quick fix, but seems to solve the issue on Windows.
If we try to match the behavior to v4, the fix will take a bit more work. …
=> Fix an issue that preventing the use of "extends:" to define the inheritance tree on Windows

tests/UnitTests/CacheResourceTests/File/CacheResourceFileTest.php
This PR fixes unit tests to enable to run CacheResourceFileTest.php on Windows. (Related PR: #1046 )
Some unit tests in CacheResourceFileTest.php now take the directory separator of Windows into account.
Test Results after modification:
```
> php .\vendor\phpunit\phpunit\phpunit --filter=CacheResourceFileTest
PHPUnit 8.5.39 by Sebastian Bergmann and contributors.
...............................................................   63 / 63 (100%)
Time: 56.96 seconds, Memory: 18.00 MB
OK (63 tests, 258 assertions)
```
Current Test Results:
(from https://github.com/smarty-php/smarty/pull/1046#issuecomment-2257067168 )
```
1) CacheResourceFileTest::testGetCachedFilepathSubDirs
Failed asserting that 'D:\a\smarty\smarty\tests\UnitTests\CacheResourceTests\File\cache\ca\25\46\ca2546820bc1a72783da8406 …
```
=> Fix unit tests to enable to run CacheResourceFileTest.php on Windows

tests/UnitTests/TemplateSource/NullCoalescingTest.php, tests/UnitTests/TemplateSource/TernaryTest.php
This PR fixes unit tests to enable to run NullCoalescingTest.php and TernaryTest.php on Windows. (Related PR: #1046 )
Current Test Results:
(from https://github.com/smarty-php/smarty/pull/1046#issuecomment-2257067168 )
```
45) NullCoalescingTest::testUndefined
chdir(): No such file or directory (errno 2)
D:\a\smarty\smarty\tests\PHPUnit_Smarty.php:107
D:\a\smarty\smarty\tests\UnitTests\TemplateSource\NullCoalescingTest.php:7
46) NullCoalescingTest::testOther with data set #0 (null, 'undefined')
chdir(): No such file or directory (errno 2)
D:\a\smarty\smarty\tests\PHPUnit_Smarty.php:107
D:\a\smarty\smarty\tests\UnitTests\TemplateSource\NullCoalescingTest.php:7
47) NullCoalescingTest::testOther with data set #1 ('blah', 'blah')
chdir(): No such file or directory (errno 2) …
```
=> Fix unit tests to enable to run NullCoalescingTest.php and TernaryTest.php on Windows

.github/workflows/ci.yml
Thank you for your developing!
This PR makes it possible to run tests on Windows with GitHub Actions.
Because I saw the comment in #1018 .
https://github.com/smarty-php/smarty/issues/1018#issuecomment-2137375455
I have adjusted the CI results to always be green on Windows because there are tests that fail on Windows now.
I would like to see “exit 0” and "continue-on-error: true" removed in the future.
I would be happy if this PR could help solve the issue.
=> Update a workflow file for GitHub Actions to test on Windows

.github/workflows/ci.yml, README.md, docker-compose.yml, run-tests-for-all-php-versions.sh, src/Cacheresource/Base.php, src/Cacheresource/Custom.php, src/Cacheresource/File.php, src/Cacheresource/KeyValueStore.php, src/Compiler/CodeFrame.php, src/Compiler/Template.php, src/CompilerException.php, src/Resource/BasePlugin.php, src/Resource/CustomPlugin.php, src/Resource/ExtendsPlugin.php, src/Resource/FilePlugin.php, src/Resource/StreamPlugin.php, src/Resource/StringPlugin.php, src/Runtime/InheritanceRuntime.php, src/Template.php, src/Template/Source.php, src/TemplateBase.php, tests/PHPUnit_Smarty.php, tests/UnitTests/CacheResourceTests/_shared/PHPunitplugins/resource.filetest.php, tests/UnitTests/ResourceTests/Custom/Ambiguous/PHPunitplugins/resource.ambiguous.php, tests/UnitTests/ResourceTests/ResourcePlugins/PHPunitplugins/resource.db.php, tests/UnitTests/ResourceTests/ResourcePlugins/PHPunitplugins/resource.db2.php, tests/UnitTests/ResourceTests/ResourcePlugins/PHPunitplugins/resource.db3.php, tests/UnitTests/ResourceTests/ResourcePlugins/PHPunitplugins/resource.db4.php, tests/UnitTests/__shared/resources/resource.extendsall.php, utilities/testrunners/php84/Dockerfile
This pull request updates the code base to support the deprecations introduced in PHP 8.4. It should be backwards compatible.
1. Updated the function signatures that had implicit null assignment to typed parameters. 
2. Added PHP 8.4 to the 'run tests'-shell script.
3. Bumped the PHP version in the README.md
=> Add PHP 8.4 support to Smarty

docs/getting-started.md
The supported PHP version on the "getting-started" page of the documentation was up to 8.3, so I fixed it to 8.4.
=> Update PHP8.3 to 8.4 in getting-started.
